services:
  - type: web
    name: chat-app-backend
    env: node
    rootDir: chat-app-backend
    buildCommand: npm install && npm run build
    startCommand: npm run develop
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: DATABASE_FILENAME
        value: .tmp/data.db
      - key: JWT_SECRET
        value: "gMdDFpk3WHt2GkUFnj2YJQ=="
      - key: ADMIN_JWT_SECRET
        value: "dafjahf67987s$^dasklfna"
      - key: API_TOKEN_SALT
        value: "uiafiauhfhi675$^%&*fsa"
      - key: APP_KEYS
        value: "a0b1c2d3f4f5g6h7,b8c9d0e6f2g3h4i5,j6k7l8m9n0p1q2r3,s4t5u4v7w8x9y0z1"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: DATABASE_CLIENT
        value: sqlite
      - key: PLUGIN_USERS_PERMISSIONS_JWT_SECRET
        value: "gMdDFpk3WHt2GkUFnj2YJQ=="
    port: 10000 