services:
  - type: web
    name: chat-app-backend
    env: node
    rootDir: chat-app-backend
    buildCommand: NODE_ENV=production npm install && npm run build
    startCommand: NODE_OPTIONS="--max-old-space-size=256" node server.js
    port: 10000
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 10000 