services:
  - type: web
    name: chat-app-backend
    env: node
    rootDir: chat-app-backend
    buildCommand: npm install && npm run build
    startCommand: npm run develop
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: DATABASE_FILENAME
        value: .tmp/data.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        value: "toBeModified1,toBeModified2"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: DATABASE_CLIENT
        value: sqlite 