services:
  - type: web
    name: chat-app-backend
    env: node
    rootDir: chat-app-backend
    buildCommand: npm install --production=false && npm run build
    startCommand: node --optimize-for-size --max-old-space-size=460 server.js
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 