services:
  - type: web
    name: chat-app-backend
    env: node
    rootDir: chat-app-backend
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production npm run start
    port: 10000
    envVars:
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512" 