services:
  - type: web
    name: chat-app-websocket
    env: node
    rootDir: chat-websocket-server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001 