services:
  - type: web
    name: chat-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-url.onrender.com
      - key: VITE_WEBSOCKET_URL
        value: https://your-websocket-url.onrender.com 