services:
  - type: web
    name: chat-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://chat-app-backend-w09o.onrender.com
      - key: VITE_WEBSOCKET_URL
        value: https://chat-app-websocket-abd1.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 